CREATE TABLE historial (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ciudad VARCHAR(50) NOT NULL,
  latitud DECIMAL(10, 8) NOT NULL,
  longitud DECIMAL(11, 8) NOT NULL,
  tipo VARCHAR(20) NOT NULL,
  fecha_consulta DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;